### ISSUE TITLE
restful 接口

### ISSUE THREAD

**Issue by bobohuochai** [freebyron/egg-graphql-boilerplate#11]
为什么还提供了restful 的接口？
在route 中
module.exports = (app) => {
  app.get('/', 'home.index');
  app.post('/api/auth/login', 'auth.login');
  app.post('/api/auth/register', 'auth.register');
  app.resources('users', '/api/users', app.controller.user);
};

**Comment by TokioXx** [comment]
登录注册是动作，因此使用了 RESTFUL,  graphql 更适合用于对于资源的操作。

**Comment by bobohuochai** [comment]
回复好及时=。=Thanks
关于restful 和 graphql 优势和劣势,适合用在什么地方， 有没有相关的文章可以提供。一直比较疑惑这方面的=。=

**Comment by bobohuochai** [comment]
@freebyron

**Comment by TokioXx** [comment]
这个你通过google关键词就应该可以找到比较有用的分析文章
