### ISSUE TITLE
你好想问下那个Date怎样用？

### ISSUE THREAD

**Issue by callmesoul** [freebyron/egg-graphql-boilerplate#3]
`mutation createItem {
  createItem(userID: "12323", content: "dasdasd", expire:scalar.Date()) {
    id
  }
}`

**Comment by TokioXx** [comment]
按照[这里](https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/common/scalars/date.js#L4)支持的格式传就可以了, 如果是其他格式也可以修改这里的解析方式

**Comment by callmesoul** [comment]
没看明白....

**Comment by TokioXx** [comment]
你把问题再描述详细点
