### ISSUE TITLE
可以做一个更完善点的样例吗

### ISSUE THREAD

**Issue by MinJieLiu** [freebyron/egg-graphql-boilerplate#4]
网上绝大部分 `graphql` 文档都是针对前端入门的。该模板看起来也没法继续深入。

模板提供的例子里面 `dataloader` 只针对 `user` 做了优化。

复杂的场景下，如果 `item` 有100条，那么就会执行至少100个 `item` 的查询。这看起来很不合理。如果 gql 更复杂点，那么就更无法接受了。

希望有个经典 `用户 <=> 角色 <=>  权限` 多对多关系的最佳实践。

**Comment by TokioXx** [comment]
dataloader 可以做批量的查询，并不需要每个item单独获取, 参考 [user](https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/user/connector.js#L22) 的实现。Demo仅仅演示graphql的使用，并不会涉及太复杂的业务逻辑。

**Comment by MinJieLiu** [comment]
@freebyron  `fetchByIds` 没见到有地方调用过。而且里面写的 dataloader 里面的 `fetch` 也是由 `where 
` 语句优化。
我加了很多 `item` 数据，如下图：

 ![https://minjieliu.github.io/assets/issures-image/9.png](https://minjieliu.github.io/assets/issures-image/9.png)

**Comment by MinJieLiu** [comment]
上面那张图错了，修正一下，改了一下`query` 去查询 `fetchByIds` 。如果用户有100条数据，也就要查询100次 `item`。

![https://minjieliu.github.io/assets/issures-image/11.png](https://minjieliu.github.io/assets/issures-image/11.png)

![https://minjieliu.github.io/assets/issures-image/10.png](https://minjieliu.github.io/assets/issures-image/10.png)

**Comment by TokioXx** [comment]
connector, resolver 的实现可能都会影响查询的处理，这两个地方你都正确实现了么

**Comment by MinJieLiu** [comment]
我直接用的官方例子，稍微改了一个方法的名字，让它调用了 `fetchByIds ` 而已。

`item` 的 `resolver` 这样写会影响吧：

[https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/item/resolver.js#L5](https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/item/resolver.js#L5)

我刚刚把这个方法去掉后，自己用 `seqluelize` 模型关联数据主动带出 `item` 就只有一条`sql` 了。

所以还不知道 `dataloader` 该如何写，才不会导致那么多 `sql`

**Comment by TokioXx** [comment]
user的dataloader是可以支持批量查询的，只是resolver那边并没有使用，在resolver里面使用 [fetchByIds](https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/user/connector.js#L22)就可以了

**Comment by MinJieLiu** [comment]
我刚刚在 `resolver` 里面使用了 `fetchByIds` 才出现的多个 `sql`。
```js
users(root, { id }, ctx) {
  return ctx.connector.user.fetchByIds(id);
},
```
所以我感觉 user 里面的 `dataloader` 不支持批量查询。

![https://minjieliu.github.io/assets/issures-image/11.png](https://minjieliu.github.io/assets/issures-image/11.png)

**Comment by TokioXx** [comment]
建议你先单独使用dataloader测试，确认代码是按期望的运行

**Comment by dmodaii** [comment]
@freebyron @MinJieLiu 连续发送两次， 两次重复执行相同sql， 既没有缓存， 也没批量,  
```javascript
// resolvers.js
   users(root, { id }, ctx) {
      return ctx.connector.user.fetchByIds(id);
    }

// postman 请求
{
"query":  "{users(id: [15, 18, 19]){id, name, items {id, done, content}}}"
}
```
![image](https://user-images.githubusercontent.com/16190100/38495470-49143976-3c2c-11e8-93ac-fff43e967142.png)

**Comment by MinJieLiu** [comment]
@dmodaii 查询的是 users ，它已经是批量了 
![image](https://user-images.githubusercontent.com/6167727/38534867-1f7a2d1e-3cb3-11e8-9bd5-a7f638de7014.png)
至于你 items 里面的批量你没有实现它。

**Comment by dmodaii** [comment]
@MinJieLiu 我重新修改了items使之可以批量， 但是应该返回怎么样的结果才能正确的匹配到原来的userid并返回正确的json给前端
![image](https://user-images.githubusercontent.com/16190100/38542922-b6a9cfba-3cd5-11e8-839a-fdf55d0a6177.png)
> TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: [objectObject].

批量后不知道返回怎么样的数据格式对应每个user_id了


```
  constructor(ctx) {
    this.ctx = ctx;
    this.proxy = ctx.app.model.Item;
    this.loader = new DataLoader(this.fetch.bind(this));
  }

  fetch(ids) {
    const users = this.proxy.findAll({
      where: {
        user_id: {
          $in: ids,
        },
      },
    }).then((us) => {
      let res = {};
      ids.forEach((id) => {
        res[id] = [];
        us.forEach((model) => {
          if (id === model.user_id) {
            res[id].push(model.toJSON());
          }
        });
      });
      return res;
      // us.map(u => u.toJSON())
    });
    return users;
  }

  fetchByIds(ids) {
    return this.loader.loadMany(ids);
  }

  fetchById(id) {
    return this.loader.load(id);
  }
```

**Comment by MinJieLiu** [comment]
@dmodaii 我是这么做的，把 Role 换成 Item

```js
async showByUserId(userIdArr) {
  const { User, Role } = this.ctx.model;
  const list = await Role.findAll({
    include: [{
      model: User,
      attributes: ['id'],
      where: { id: userIdArr },
      required: true,
    }],
    raw: true,
  });
  // 关键所在
  return userIdArr.map(currentId => list.filter(n => n['users.id'] === currentId));
}
```

**Comment by neeboo** [comment]
schema stitching没法用
