### ISSUE TITLE
进行单元测试出现如下问题：Schema must be an instance of GraphQLSchema

### ISSUE THREAD

**Issue by wangxiaochuang** [freebyron/egg-graphql-boilerplate#5]
我用的版本如下：
  "dependencies": {
    "dataloader": "^1.4.0",
    "egg": "^2.2.1",
    "egg-graphql": "^2.1.0",
    "egg-scripts": "^2.5.0",
    "egg-sequelize": "^3.1.2",
    "graphql": "^0.13.2",
    "lodash": "^4.17.5",
    "mysql2": "^1.5.3",
    "npm": "^5.8.0"
  },  
，在执行这里的时候：
const data = yield ctx.service.graphql.query(query);
    assert.equal(data.data.user.id, user.id);
    assert.equal(data.data.user.name, user.name);

**Comment by TokioXx** [comment]
这个是 graphql 的版本不对，重新安装依赖试试
